version: '2'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
       - 5432:5432
    volumes:
       - ./postgres:/var/lib/postgresql/data
    env_file: 
       - environment/.tsenv
  grafana:
    image: grafana/grafana:9.5.3
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: environment/.gfenv
    volumes:
      - grafana-data:/var/lib/grafana
    user: '0'